site_name: One Suite Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.footer
    - toc.integrate
    - navigation.expand  # Expands only the current section
  palette:
    scheme: default

markdown_extensions:
  - toc:
      permalink: true
      title: Table of Contents
      toc_depth: 2

nav:
  - Home: index.md
  - OneLead:
        - Overview: onelead/index.md
        - Installation: onelead/installation.md
        - Meta:
            - Overview: onelead/meta/index.md
            - Setup: onelead/meta/setup.md
            - Meta Lead Testing: onelead/meta/meta_lead_testing.md
            - Meta Form Mapping: onelead/meta/meta_form_mapping.md
  - OneInbox:
      - Overview: oneinbox/index.md
      - Instagram: oneinbox/instagram/index.md
      - Messenger: oneinbox/messenger/index.md
      - WhatsApp: oneinbox/whatsapp/index.md

